FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo
ENV DESTDIR=/install
RUN perl Configure.pl
RUN make -j8 install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
ENV LD_LIBRARY_PATH=/install/repo/install/lib/
